# Generated by Django 3.0.8 on 2020-08-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_check', '0005_auto_20200813_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='PASSP_NUMBER',
            field=models.BinaryField(max_length=6),
        ),
    ]
