# Generated by Django 3.0.8 on 2020-08-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_check', '0007_auto_20200816_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='NUM_SERIES',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
