# Generated by Django 3.0.8 on 2020-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_check', '0004_auto_20200813_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='PASSP_NUMBER',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='passport',
            name='PASSP_SERIES',
            field=models.CharField(max_length=4),
        ),
    ]
