# Generated by Django 3.0.8 on 2020-08-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport_check', '0005_auto_20200813_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='PASSP_NUMBER',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='PASSP_SERIES',
            new_name='series',
        ),
    ]
